---
name: Linting

on:
  pull_request:

jobs:
  linting:
    name: flake8
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: x64

      - name: install tox
        run: python -m pip install tox tox-gh-actions

      - name: flake8 via tox
        run: tox -e flake8
